### ISSUE TITLE
Adjust Minimum Value on V-Bar/H-Bar

### ISSUE THREAD

**Issue by bburnsy** [eLERT-AdvancedMonitoringSystem/eLertVision-Issue-Tracker#25]
Adjust the minimum value on the vertical bar graph and horizontal bar graph so that the minimum value of the the data is not cut off when you are zoomed in on a graph.

**Comment by jjenksy** [comment]
We now calculate the high and lowest values in the sets and add to the high end of the scale and subtract from the low end of the scale in order to always show the graph when in dynamic mode.
