### ISSUE TITLE
Chart examples when selected do not fit completely on the drop zone

### ISSUE THREAD

**Issue by mkidd777** [eLERT-AdvancedMonitoringSystem/eLertVision-Issue-Tracker#6]
When selecting a chart, the chart examples do not fit completely on the drop zone.
This is at a screen resolution of 1920x1080 using Google Chrome

![image](https://cloud.githubusercontent.com/assets/19628553/26731025/5b6f870a-4778-11e7-8e64-3a78f07f8b33.png)

**Comment by jjenksy** [comment]
I assigned to Austin but I believe he fixed this in the lastest version but it has not been loaded on the server yet.

**Comment by mkidd777** [comment]
I will discontinue bug testing until the new version is installed.

**Comment by jjenksy** [comment]
Fixed for 1080p
