### ISSUE TITLE
When placing delected data points in the Points Container the order of data points does not maintain the order they were selected

### ISSUE THREAD

**Issue by mkidd777** [eLERT-AdvancedMonitoringSystem/eLertVision-Issue-Tracker#7]
When placing delected data points in the Points Container the order of data points does not maintain the order they were selected.

For example on UPS 2, I selected the following data points in the following order:
1. Input_Voltage_AB
2. Input_Voltage_BC
3. Input_Voltage_CA

When Input_Voltage_CA is added to the Points Container the points are resorted.
![image](https://cloud.githubusercontent.com/assets/19628553/26731632/4bcb5778-477a-11e7-9d91-4e69729b7568.png)

![image](https://cloud.githubusercontent.com/assets/19628553/26731647/55ca5990-477a-11e7-81dc-3d750b5b635d.png)

**Comment by jjenksy** [comment]
This is only a UI issue and does not effect the rendered graph
